services:
   db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata: 