export enum OrderStatusEnum {
  CREATED = 'CREATED',
  ACCEPTED = 'ACCEPTED',
  PREPARATION = 'PREPARATION',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
}
